apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
  namespace: webapps
subjects:
  kind: ServiceAccount
  name: jenkins
  namespace: webapps
roleRef:
  kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io